{
    'name': 'Lieb Puros Heridos',
    'version': '18.0.1.0.0',
    'summary': 'Flujo de Puros Heridos y Tabaco para Pipa',
    'author': 'Guillermo Alvarado',
    'category': 'Inventory',
    'license': 'LGPL-3',
    'depends': ['stock', 'product', 'sale', 'point_of_sale'],
    'data': [
        'security/ir.model.access.csv',
        'data/product_attribute.xml',
        'data/product_category.xml',
        'data/stock_location.xml',
        'data/product_template.xml',
        'data/sequences.xml',
        'views/product_attribute_value_views.xml',
        'views/acta_clasificacion_views.xml',
    ],
    'post_init_hook': 'post_init_hook',
    'installable': True,
    'application': False,
    'auto_install': False,
}
